Resources:
  LambdaWarmupRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: LambdaWarmupRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: myPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow # WarmUp lamda to send logs to CloudWatch
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow # WarmUp lamda to manage ENIS (only needed if deploying to VPC, https://docs.aws.amazon.com/lambda/latest/dg/vpc.html)
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DetachNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: "*"
              - Effect: 'Allow' # WarmUp lamda to invoke the functions to be warmed
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                - Fn::Join:
                  - ':'
                  - - arn:aws:lambda
                    - Ref: AWS::Region
                    - Ref: AWS::AccountId
                    - function:${self:service}-${opt:stage, self:provider.stage}-*
