Resources:
  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tables.todos.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tables.todos.readCapacity}
        WriteCapacityUnits: ${self:custom.tables.todos.writeCapacity}

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tables.items.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: todo_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: todo_id
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tables.items.readCapacity}
        WriteCapacityUnits: ${self:custom.tables.items.writeCapacity}
